### ISSUE TITLE
Just a question from a Hugo newbie

### ISSUE THREAD

**Issue by yoxel** [Mitrichius/hugo-theme-anubis#137]
Hi Dmitry, 

I like the theme!

I am new to Hugo, and just installed it and your theme for the first time.
Could you help me understand how an About and Tags pages can be added like on your demo blog.

Thank you.

**Comment by Mitrichius** [comment]
Hi!

**About** — you should create `about.md` and fill it like a common post (meta + text). 
**Tags** — just add a link to config, page is created on build.
And add both to the config - menu section.

YAML-format
```
menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 1
  - identifier: tags
    name: Tags
    title: tags
    url: /tags/
    weight: 2
```

TOML-format
```
[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2
```
