### ISSUE TITLE
custom css: hugo exits with 'EXECUTE-AS-TEMPLATE: failed to transform "css/main.css"'

### ISSUE THREAD

**Issue by stephen-fox** [Mitrichius/hugo-theme-anubis#153]
Hello,

I have been experimenting with newer versions of hugo and your awesome theme.
In doing so, I ran into a similar issue as the one described in issue #87 where hugo
exits with the following error:

```sh
# Installed with nix-env.
hugo server -D
Start building sites … 
hugo v0.98.0+extended darwin/arm64 BuildDate=unknown
Error: Error building site: EXECUTE-AS-TEMPLATE: failed to transform "css/main.css" (text/css): template: css/main.css:733:14: executing "css/main.css" at <$custom.Content>: nil pointer evaluating resource.Resource.Content
Built in 58 ms
```

I am using the `customCSS` setting which points at a single file. If I comment out this
setting, hugo works as expected. My CSS file provides a few minor formatting tweaks
related to footnotes:

```css
a.footnote-ref::before {
    content: '[';
}

a.footnote-ref::after {
    content: ']';
}

/* https://discourse.gohugo.io/t/footnote-styling/114/6 */
sup, sub {
    vertical-align: baseline;
    position: relative;
    top: -0.4em;
}

sub {
    top: 0.4em;
}
```

I tried to remove portions of the CSS file. Even with an empty CSS file,
hugo exits with the same error. As suggested in issue 87, I tried both
building hugo myself (with `go build -o hugo -tags extended *.go`),
and installing it using my package manager (nix), which also installed
the extended variant. Both builds result in the same behavior.

This issue **does not** occur when using an older anubis commit (350ae2d).

I was able to reproduce the error with anubis commit edc508fa (current
commit pointed to by `master`). I tried the latest hugo source code
revision and v0.98.0 and both versions reproduced the issue.
