### ISSUE TITLE
Adding new hyperlinks to the menu

### ISSUE THREAD

**Issue by bool3max** [Mitrichius/hugo-theme-anubis#72]
The example config has this inside of it: 

```
menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
```

I've tried adding additional links to the menu, but it doesn't work: 

```
[menu]
  [[menu.main]]
      identifier = "archive"
      name = "Archive"
      title = "Archive"
      url = "/posts/"
      weight = 0.0
  [[manu.test]]
      identifier = "test"
      name = "Test"
      title = "Test"
      url = "https://google.com"
      weight = 1.0
```

Is this not supported by anubis or is my TOML syntax wrong?
