### ISSUE TITLE
Deploying on github pages missing styling

### ISSUE THREAD

**Issue by SntTGR** [Mitrichius/hugo-theme-anubis#81]
Hello! I really like this theme but had some problems trying to set it up online 

Im using a quickstart page with only one post and deploying with this theme doesn't show the styling (at least in github pages)
Using the local ```hugo server``` works fine.
I also tried using another theme 'ananke' and it shows styling. 

https://snttgr.github.io 
SntTGR/SntTGR.github.io@2c0814e9604deb6f51632e4e429fc8e96bb1a04b
![image](https://user-images.githubusercontent.com/30510907/109371831-6d9e3380-7885-11eb-8c54-28cdcaf23021.png)
links work! no 404s

Made sure to put the correct url in `baseUrl:` and inspected the page to make sure the stylesheet correctly referenced the css file, but somehow the styling doesn't work.

Im using the example config .yaml with a few thing commented-out

```yaml
languageCode: "en-us"
baseUrl: "https://snttgr.github.io"
title: "Anubis"
theme: "anubis"
paginate: 10

#disqusShortname: yourdiscussshortname
#googleAnalytics: UA-123-45
#enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "John Doe"
  email: mail@example.org # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: ""
  #images:
  #  - images/og-featured.png # relative path to "static" directory
  #customCSS:
  #  - css/my.css # relative path to "assets" directory (don't use main.css filename)
  #customJS:
  #  - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false
  # utteranc.es support
  #utterancesRepo: ""  # mandatory
  #utterancesTheme: "" # optional
  #utterancesIssue: "" # optional
  #utterancesLabel: "" # optional
#  webmentions:
#    login: hugo-theme-anubis
#    pingback: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
```
